### ISSUE TITLE
unable to connect components

### ISSUE THREAD

**Issue by jammcpe** [MittyRobotics/tko-electronics-sim#5]
![image](https://user-images.githubusercontent.com/33586367/102177042-8a66c580-3e57-11eb-81bf-a763b01c7cde.png)
![image](https://user-images.githubusercontent.com/33586367/102177070-994d7800-3e57-11eb-8c4b-857c484a7941.png)
Unable to connect components 18awg components together errors above defaults to 22awg wire and then you cannot change the wire gauge you have to start wires off in space and then connect both ends (specifically power wires)
![image](https://user-images.githubusercontent.com/33586367/102177279-10830c00-3e58-11eb-83d1-849f33853595.png)
(i had to do this by starting a new wire and then connecting them.

**Comment by rohan-bansal** [comment]
thanks for opening an issue! we'll get around to fixing these bugs once break starts for the team (about a week or so). this issue is on the todo list.

**Comment by liqyn** [comment]
![Screen Shot 2021-06-05 at 3 38 47 PM](https://user-images.githubusercontent.com/54689920/120907157-21952480-c614-11eb-9049-d2d98753637c.png)
Can't seem to replicate the issue
