### ISSUE TITLE
Error: Does not work if I don't add a PCM

### ISSUE THREAD

**Issue by cghercoias** [MittyRobotics/tko-electronics-sim#7]
Hello - Great work guys, it certainly helps us show students how a robot should be wired correctly.
There is a little problem. We get an error if we don't add a PCM, even if we don't need one. Our robot is not using pneumatics.

**Comment by rohan-bansal** [comment]
Got it! We'll check this out, thanks for the report.

**Comment by liqyn** [comment]
Sorry about the long delay, school meant we had to shift our priorities - we will work on fixing this and other issues in the following weeks.

**Comment by liqyn** [comment]
Fixed - will be included in a new release

**Comment by cghercoias** [comment]
I appreciate it so much. Thank you!

*-- Mr. Catalin Ghercoias*

*Electrical/Electronics Mentor*
Team 20 - The Rocketeers.
Shenendehowa High School
Clifton Park, NY
***@***.***
